[dev]
   command = "yarn dev"
   port = 9000
[build]
  command = "yarn generate"
  publish = "dist"
  functions = 'back'

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"